<a href="https://colab.research.google.com/github/ManishaArugula/Finance-Performance-Analysis/blob/main/Finance_Performance_Analysis_Data_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project analyses the financial performance of private start-up companies that went public 5 years ago. Financial information, such as income statements, balance sheets, and cash flows, is used to create the final data frame. Historical data is used to calculate the average closing price and total stock volume sold between 2020-2025.
Python is used as an ETL tool to extract the data from Yahoo Financials, perform data transformations to consolidate the necessary columns and load the data into an Excel sheet.

# 1. Import Libraries

In [ ]:
##Loading the libraries
import pandas as pd
import numpy as np

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import yfinance as yf

In [ ]:
pd.options.display.float_format = '{:.2f}'.format

# 2. Extract Initial Public Offering (IPO) Data

In [ ]:
## extracting IPO data for funding circle
ticker1 = yf.Ticker('FCH.L')
income_stmt_fch = ticker1.financials.T
bal_sheet_fch = ticker1.balance_sheet.T
cash_flow_fch = ticker1.cash_flow.T

In [ ]:
## extracting IPO data for One Saivngs Bank
ticker2 = yf.Ticker('LINV.L')
income_stmt_linv = ticker2.financials.T
bal_sheet_linv = ticker2.balance_sheet.T
cash_flow_linv = ticker2.cash_flow.T

In [ ]:
cash_flow_fch.head()

,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Issuance Of Capital Stock,Capital Expenditure,End Cash Position,Beginning Cash Position,Effect Of Exchange Rate Changes,Changes In Cash,...,Other Non Cash Items,Stock Based Compensation,Provisionand Write Offof Assets,Depreciation And Amortization,Amortization Cash Flow,Depreciation,Gain Loss On Investment Securities,Net Foreign Currency Exchange Gain Loss,Gain Loss On Sale Of Business,Net Income From Continuing Operations
2024-12-31,-79300000.00,-33700000.00,-6000000.00,52600000.00,500000.00,-11900000.00,187600000.00,221400000.00,100000.00,-33900000.00,...,-6300000.00,8100000.00,1700000.00,13000000.00,9800000.00,3200000.00,NaN,-8700000.00,-9800000.00,9200000.00
2023-12-31,-37800000.00,-1800000.00,-44300000.00,55800000.00,0.00,-12200000.00,221400000.00,177700000.00,-800000.00,44500000.00,...,-7800000.00,5600000.00,900000.00,16700000.00,12400000.00,4300000.00,NaN,0.00,0.00,-33200000.00
2022-12-31,-22000000.00,-8700000.00,-187000000.00,0.00,100000.00,-13900000.00,177700000.00,224000000.00,3800000.00,-50100000.00,...,-4500000.00,4700000.00,-100000.00,15200000.00,10100000.00,5100000.00,-4800000.00,NaN,NaN,-12900000.00
2021-12-31,89100000.00,0.00,-491900000.00,208200000.00,400000.00,-9400000.00,224000000.00,103300000.00,900000.00,119800000.00,...,-3600000.00,8500000.00,-1900000.00,13900000.00,8000000.00,5900000.00,-28600000.00,NaN,NaN,64100000.00
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,118300000.00,NaN,NaN,NaN

# 3. Get Finance & Revenue Data

## Income Statement Columns
1. Net Income
2. Operating Income & Expense : Operating Efficiency Ratio
3. Gross Profit: Gross Profit Margin
4. Cost of Revenue : Cost of Goods & Services
5. Revenue: Total Revenue, Revenue Growth Rate, Operating Efficiency Ratio, Profit Margin, Gross Profit Margin

In [ ]:
income_stmt_linv.columns

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Rent Expense Supplemental',
       'Total Operating Income As Reported', 'Diluted Average Shares',
       'Basic Average Shares', 'Diluted EPS', 'Basic EPS',
       'Diluted NI Availto Com Stockholders', 'Net Income Common Stockholders',
       'Otherunder Preferred Stock Dividend', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Special Income Charges', 'Other Special Charges', 'Write Off',
       'Net Non Operating Interest Income Expense', 'Total Other Finance Cost',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense',
       'Selling General And Administration',
       'General And Administrative Expense', 'Gross Profit', 'Cost Of Revenue',
       'Total Revenue', 'Operating Revenue'],
      dtype='object')

In [ ]:
#extract only columns that have a direct meaning or can be indirectly calculated without too many calculations
#Cost of Revenue : Cost of Goods and Services (CoGS)
fin_cols=['Net Income','Operating Income', 'Operating Expense','Gross Profit', 'Cost Of Revenue', 'Total Revenue']
income_fch = income_stmt_fch[fin_cols].copy()
income_linv =  income_stmt_linv[fin_cols].copy()
income_linv

,Net Income,Operating Income,Operating Expense,Gross Profit,Cost Of Revenue,Total Revenue
2025-03-31,-1600000.00,13600000.00,36200000.00,49800000.00,38800000.00,88600000.00
2024-03-31,-23900000.00,-9000000.00,42300000.00,33300000.00,47400000.00,80700000.00
2023-03-31,11400000.00,18600000.00,34300000.00,52900000.00,27100000.00,80000000.00
2022-03-31,10900000.00,11100000.00,31900000.00,43000000.00,38300000.00,81300000.00
2021-03-31,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
bal_sheet_fch.columns

Index(['Treasury Shares Number', 'Ordinary Shares Number', 'Share Issued',
       'Net Debt', 'Total Debt', 'Tangible Book Value', 'Invested Capital',
       'Working Capital', 'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Other Equity Interest', 'Retained Earnings',
       'Additional Paid In Capital', 'Capital Stock', 'Common Stock',
       'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Long Term Provisions', 'Current Liabilities',
       'Other Current Liabilities',
       'Current Debt And Capital Lease Obligation',
       'Current Capital Lease Obligation', 'Current Debt',
       'Current Provisions', 'Payables', 'Other Payable', 'Total Tax Payable',
       'Accounts Payable', 'Total Assets', 'Total Non Current Assets',
       'Non Current Deferred Taxes Assets', 'Investmentin Financial Assets',
       'Financial Assets Designatedas Fair Value Through Profitor Loss Total',
       'Long Term Equity Investment', 'Investmentsin Associatesat Cost',
       'Goodwill And Other Intangible Assets', 'Other Intangible Assets',
       'Goodwill', 'Net PPE', 'Accumulated Depreciation', 'Gross PPE',
       'Machinery Furniture Equipment', 'Buildings And Improvements',
       'Properties', 'Current Assets', 'Restricted Cash', 'Prepaid Assets',
       'Other Receivables', 'Taxes Receivable', 'Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Cash And Cash Equivalents'],
      dtype='object')

## Balance Sheet Columns
1. Current Assest & liabilities : To show Current Ratio
2. Cash Cash Equivalent and Short Term Investments is considered as Cash Availability

In [ ]:
# Cash and Cash Equivalents and Short Term Investments is considered as the "Cash available". cash equivalents + short-term investments,
# such as marketable securities (like short-term bonds or CDs) that can be quickly converted to cash

#Initially thought of using Cash and Cash Equivalents which is "pure cash " as "cash Available" but then chose a broader term like the above term"
bal_cols =['Current Assets','Current Liabilities','Cash Cash Equivalents And Short Term Investments']
bal_fch = bal_sheet_fch[bal_cols].copy()
bal_linv = bal_sheet_linv[bal_cols].copy()
bal_fch.rename(columns={'Cash Cash Equivalents And Short Term Investments':'Cash Available'}, inplace=True)
bal_linv.rename(columns={'Cash Cash Equivalents And Short Term Investments':'Cash Available'}, inplace=True)

In [ ]:
bal_fch

            Current Assets  Current Liabilities  Cash Available
2024-12-31    307400000.00         135100000.00    187600000.00
2023-12-31    311500000.00         117700000.00    221400000.00
2022-12-31    279300000.00          63700000.00    177700000.00
2021-12-31    401900000.00         187000000.00    190200000.00
2020-12-31             NaN                  NaN             NaN

In [ ]:
cash_flow_fch.columns

Index(['Free Cash Flow', 'Repurchase Of Capital Stock', 'Repayment Of Debt',
       'Issuance Of Debt', 'Issuance Of Capital Stock', 'Capital Expenditure',
       'End Cash Position', 'Beginning Cash Position',
       'Effect Of Exchange Rate Changes', 'Changes In Cash',
       'Financing Cash Flow', 'Net Common Stock Issuance',
       'Common Stock Payments', 'Common Stock Issuance',
       'Net Issuance Payments Of Debt', 'Net Short Term Debt Issuance',
       'Short Term Debt Payments', 'Net Long Term Debt Issuance',
       'Long Term Debt Payments', 'Long Term Debt Issuance',
       'Investing Cash Flow', 'Interest Received Cfi',
       'Dividends Received Cfi', 'Net Investment Purchase And Sale',
       'Sale Of Investment', 'Purchase Of Investment',
       'Net Business Purchase And Sale', 'Sale Of Business',
       'Purchase Of Business', 'Net Intangibles Purchase And Sale',
       'Purchase Of Intangibles', 'Net PPE Purchase And Sale',
       'Purchase Of PPE', 'Operating Cash Flow', 'Taxes Refund Paid',
       'Change In Working Capital', 'Change In Payable',
       'Change In Receivables', 'Other Non Cash Items',
       'Stock Based Compensation', 'Provisionand Write Offof Assets',
       'Depreciation And Amortization', 'Amortization Cash Flow',
       'Depreciation', 'Gain Loss On Investment Securities',
       'Net Foreign Currency Exchange Gain Loss',
       'Gain Loss On Sale Of Business',
       'Net Income From Continuing Operations'],
      dtype='object')

## Cash Flow Columns
1. Operating Cash Flow: Cash inflow - Cash Outflow
2. Capital Expenditure: Total money spent on company growth and operation for future

In [ ]:
# operating cash flow is considered as the cash flow (cash inflow - cash outflow) essential to calculate the burn rate and the runaway
cash_fch  = cash_flow_fch[['Operating Cash Flow','Capital Expenditure']].copy()
cash_linv  = cash_flow_linv[['Operating Cash Flow','Capital Expenditure']].copy()

# 4. Combining the data columns selected from financials into one dataframe

In [ ]:
#combining the selected columns
fch = income_fch.join([bal_fch, cash_fch], how='outer')
fch.fillna(0, inplace=True)
linv = income_linv.join([bal_linv, cash_linv], how='outer')
linv.fillna(0, inplace=True)

In [ ]:
fch.index.year

Index([2024, 2023, 2022, 2021, 2020], dtype='int32')

In [ ]:
# Creating a year column from the date
fch['Year'] = fch.index.year
linv['Year'] = linv.index.year

# 5. Fetch the stock data to generate the average close value and total volume

In [ ]:
stock_fch = ticker1.history(start = '2020-01-01', end ='2024-12-31')
stock_linv = ticker2.history(start = '2020-01-01', end ='2024-12-31')

In [ ]:
#extracting the avg closing value and the total volume of stocks sold for the year
stock_value_fch = stock_fch.resample('YE').agg({'Close':'mean',
                          'Volume':'sum'}).rename(columns={'Close':'Avg Close Price',
                                                           'Volume':'Total Volume'})
stock_value_linv = stock_linv.resample('YE').agg({'Close':'mean',
                          'Volume':'sum'}).rename(columns={'Close':'Avg Close Price',
                                                           'Volume':'Total Volume'})

In [ ]:
stock_value_fch.index.year

Index([2020, 2021, 2022, 2023, 2024], dtype='int32', name='Date')

In [ ]:
#creating the year column for stocks
stock_value_fch['Year'] = stock_value_fch.index.year
stock_value_linv['Year'] = stock_value_linv.index.year

# 6. Merge the financials and the stock data into a final document

In [ ]:
# combining the financials and the stock data on Year using merge statement
fch_df = pd.merge(fch, stock_value_fch, on='Year').set_index('Year')
linv_df = pd.merge(linv, stock_value_linv, on='Year').set_index('Year')

# 7. Load the dataframe to a csv file

In [ ]:
fch_df.drop([2020,2021], axis=0, inplace=True)
fch_df

,Net Income,Operating Income,Operating Expense,Gross Profit,Cost Of Revenue,Total Revenue,Current Assets,Current Liabilities,Cash Available,Operating Cash Flow,Capital Expenditure,Avg Close Price,Total Volume
Year,,,,,,,,,,,,,
2024,8600000.00,800000.00,84700000.00,85500000.00,76200000.00,161700000.00,307400000.00,135100000.00,187600000.00,-67400000.00,-11900000.00,88.16,282839515
2023,-38300000.00,-9900000.00,71400000.00,61500000.00,68200000.00,129700000.00,311500000.00,117700000.00,221400000.00,-25600000.00,-12200000.00,48.95,43451678
2022,-6900000.00,-12900000.00,78000000.00,65100000.00,90600000.00,155700000.00,279300000.00,63700000.00,177700000.00,-8100000.00,-13900000.00,60.22,139683043

In [ ]:
linv_df.drop([2021], inplace=True)
linv_df

,Net Income,Operating Income,Operating Expense,Gross Profit,Cost Of Revenue,Total Revenue,Current Assets,Current Liabilities,Cash Available,Operating Cash Flow,Capital Expenditure,Avg Close Price,Total Volume
Year,,,,,,,,,,,,,
2024,-23900000.00,-9000000.00,42300000.00,33300000.00,47400000.00,80700000.00,543000000.00,25600000.00,53200000.00,28600000.00,-3200000.00,27.31,5503910
2023,11400000.00,18600000.00,34300000.00,52900000.00,27100000.00,80000000.00,1174500000.00,23700000.00,40400000.00,-192700000.00,-6500000.00,60.87,18640671
2022,10900000.00,11100000.00,31900000.00,43000000.00,38300000.00,81300000.00,1332400000.00,47200000.00,99300000.00,-147300000.00,-3400000.00,153.69,8714439

In [ ]:
fch_df.columns = fch_df.columns.str.replace(' ', '_')
linv_df.columns = linv_df.columns.str.replace(' ', '_')

In [ ]:
fch_df.to_csv('fch.csv', index=True)
print("FCH Data successfully exported to Excel")

linv_df.to_csv('linv.csv', index=True)
print("LINV Data successfully exported to Excel")

FCH Data successfully exported to Excel
LINV Data successfully exported to Excel